config/routes.rb
AdResourceOrderx::Engine.routes.draw do
  resources :orders do
    collection do
      get :search
      get :search_results
      get :stats
      get :stats_results    
    end
    
#=begin    
    workflow_routes = Authentify::AuthentifyUtility.find_config_const('order_wf_route', 'ad_resource_orderx')
    if Authentify::AuthentifyUtility.find_config_const('wf_route_in_config') == 'true' && workflow_routes.present?
      eval(workflow_routes) 
    elsif Rails.env.test?
      member do
        get :event_action
        patch :submit
        patch :cso_approve
        patch :cso_reject
        patch :gm_approve
        patch :gm_reject
        patch :gm_rewind
        patch :sign_contract
        
      end
      
      collection do
        get :list_open_process
      end
    end
#=end
  end
  

end

app/models/ad_resource_orderx/order.rb
module AdResourceOrderx
  require 'workflow'
  class Order < ActiveRecord::Base
    include Workflow
    workflow_column :wf_state
    
    workflow do
      wf = Authentify::AuthentifyUtility.find_config_const('order_wf_pdef', 'ad_resource_orderx')
      if Authentify::AuthentifyUtility.find_config_const('wf_pdef_in_config') == 'true' && wf.present?
        eval(wf) 
      elsif Rails.env.test?  
        state :initial_state do
          event :submit, :transitions_to => :cso_reviewing
        end
        state :cso_reviewing do
          event :cso_approve, :transitions_to => :gm_reviewing
          event :cso_reject, :transitions_to => :initial_state
        end
        state :gm_reviewing do
          event :gm_approve, :transitions_to => :approved
          event :gm_reject, :transitions_to => :rejected
          event :gm_rewind, :transitions_to => :initial_state
        end
        state :approved do
          event :sign_contract, :transitions_to => :contract_signed
        end
        state :contract_signed
        state :rejected
        
      end
    end
    
    attr_accessor :sales_name, :last_updated_by_name, :customer_name, :resource_name, :wf_comment, :id_noupdate, :wf_state_noupdate, :wf_event
=begin
    attr_accessible :customer_id, :customer_po, :gm_approved, :gm_approve_date, :gm_approved_by_id, :order_date, :order_detail, :customer_name_autocomplete,
                    :order_end_date, :order_start_date, :order_total, :other_charge, :resource_id, :sales_id, :standard_price, :tax, :unit_price, :wf_state,
                    :as => :role_new
    attr_accessible :customer_id, :customer_po, :gm_approved, :gm_approve_date, :gm_approved_by_id, :order_date, :order_detail, 
                    :order_end_date, :order_start_date, :order_total, :other_charge, :resource_id, :sales_id, :standard_price, :tax, :unit_price, :wf_state,
                    :sales_name, :last_updated_by_name, :customer_name, :resource_name, :customer_name_autocomplete, :wf_comment, :id_noupdate, :wf_state_noupdate, 
                    :as => :role_update
    
    attr_accessor :start_date_s, :end_date_s, :customer_id_s, :sales_id_s, :resource_id_s, :wf_state_s, :gm_approved_s, :time_frame_s

    attr_accessible :start_date_s, :end_date_s, :customer_id_s, :sales_id_s, :resource_id_s, :wf_state_s, :gm_approved_s, :time_frame_s,
                  :as => :role_search_stats
=end                  
    belongs_to :customer, :class_name => AdResourceOrderx.customer_class.to_s
    belongs_to :resource, :class_name => AdResourceOrderx.resource_class.to_s
    belongs_to :sales, :class_name => 'Authentify::User'
    belongs_to :last_updated_by, :class_name => 'Authentify::User'

    validates :customer_id, :resource_id, :sales_id, :presence => true, :numericality => {:greater_than => 0}
    validates :order_total, :presence => true, :numericality => {:greater_than_or_equal_to => 0}
    validates :order_detail, :order_date, :presence => true
    validates :gm_approved_by_id, :numericality => {:greater_than => 0, :only_integer => true, :if => 'gm_approved_by_id.present?'}
    validates :customer_po, :uniqueness => {:scope => [:resource_id, :customer_id], :case_sensitive => false, :message => 'Duplidate customer po'}, :if => 'customer_po.present?'
    validate :dynamic_validate 
    #for workflow input validation  
    validate :validate_wf_input_data, :if => 'wf_state.present?' 
    
    def dynamic_validate
      wf = Authentify::AuthentifyUtility.find_config_const('dynamic_validate', 'ad_resource_orderx_orders')
      eval(wf) if wf.present?
    end
       
    def validate_wf_input_data
      wf = Authentify::AuthentifyUtility.find_config_const('validate_order_' + self.wf_event, 'ad_resource_orderx') if self.wf_event.present?
      if Authentify::AuthentifyUtility.find_config_const('wf_validate_in_config') == 'true' && wf.present? 
        eval(wf) 
      end
    end      
    
    def customer_name_autocomplete
      self.customer.try(:name)
    end

    def customer_name_autocomplete=(name)
      self.customer = AdResourceOrderx.customer_class.find_by_name(name) if name.present?
    end     
  end
end

app/controllers/ad_resource_orderx/application_controller.rb
module AdResourceOrderx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    include Searchx::SearchHelper
    include BizWorkflowx::WfHelper
    
    before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_action :view_in_config?
    
    helper_method :return_users, :return_misc_definitions
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
    
    #engine's
    def return_customers_by_access_right     
      access_rights, model_ar_r, has_record_access = access_right_finder('index', AdResourceOrderx.customer_class.to_s.underscore.pluralize)
      return [] if access_rights.blank?
      return model_ar_r #instance_eval(access_rights.sql_code) #.present?
    end
  end
end

app/controllers/ad_resource_orderx/orders_controller.rb
require_dependency "ad_resource_orderx/application_controller"

module AdResourceOrderx
  class OrdersController < ApplicationController
    before_action :require_employee
    before_action :load_parent_record
    
    def index
      @title = t('Orders')
      @orders = params[:ad_resource_orderx_orders][:model_ar_r]
      @orders = @orders.where(:customer_id => @customer.id) if @customer
      @orders = @orders.where(:resource_id => @resource.id) if @resource
      @orders = @orders.where(:id => @order_ids) if @order_ids
      @orders = @orders.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('order_index_view', 'ad_resource_orderx')
    end
  
    def new
      @title = t('New Order')
      @order = AdResourceOrderx::Order.new()
      @erb_code = find_config_const('order_new_view', 'ad_resource_orderx')
    end
  
    def create
      @order = AdResourceOrderx::Order.new(new_params)
      @order.last_updated_by_id = session[:user_id]
      if @order.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @customer = AdResourceOrderx.customer_class.find_by_id(params[:order][:customer_id]) if params[:order][:customer_id].present?
        @resource = AdResourceOrderx.resource_class.find_by_id(params[:order][:resource_id]) if params[:order][:resource_id].present?
        @erb_code = find_config_const('order_new_view', 'ad_resource_orderx')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Order')
      @order = AdResourceOrderx::Order.find_by_id(params[:id])
      @erb_code = find_config_const('order_edit_view', 'ad_resource_orderx')
      if @order.wf_state.present? && @order.current_state != :initial_state
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=NO Update. Record Being Processed!")
      end
    end
  
    def update
      @order = AdResourceOrderx::Order.find_by_id(params[:id])
      @order.last_updated_by_id = session[:user_id]
      if @order.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('order_edit_view', 'ad_resource_orderx')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Order Info')
      @order = AdResourceOrderx::Order.find_by_id(params[:id])
      @erb_code = find_config_const('order_show_view', 'ad_resource_orderx')
    end
    
    def list_open_process  
      index()
      @orders = return_open_process(@orders, find_config_const('order_wf_final_state_string', 'ad_resource_orderx'))  # ModelName_wf_final_state_string
    end
    
    protected
    def load_parent_record
      @customer = AdResourceOrderx.customer_class.find_by_id(params[:customer_id]) if params[:customer_id].present?
      @customer = AdResourceOrderx.customer_class.find_by_id(AdResourceOrderx::Order.find_by_id(params[:id]).customer_id) if params[:id].present?
      @resource = AdResourceOrderx.resource_class.find_by_id(params[:resource_id]) if params[:resource_id].present?
      @resource = AdResourceOrderx.resource_class.find_by_id(AdResourceOrderx::Order.find_by_id(params[:id]).resource_id) if params[:id].present?
      @order_ids = params[:order_ids] if params[:order_ids].present?  #should be array
    end
    
    private 
    def new_params
      params.require(:order).permit(:customer_id, :customer_po, :gm_approved, :gm_approve_date, :gm_approved_by_id, :order_date, :order_detail, :customer_name_autocomplete,
                    :order_end_date, :order_start_date, :order_total, :other_charge, :resource_id, :sales_id, :standard_price, :tax, :unit_price, :wf_state)
    end
    
    def edit_params
      params.require(:order).permit(:customer_id, :customer_po, :gm_approved, :gm_approve_date, :gm_approved_by_id, :order_date, :order_detail, 
                    :order_end_date, :order_start_date, :order_total, :other_charge, :resource_id, :sales_id, :standard_price, :tax, :unit_price, :wf_state)
    end
  end
end

app/helpers/ad_resource_orderx/application_helper.rb
module AdResourceOrderx
  module ApplicationHelper
  end
end

app/helpers/ad_resource_orderx/orders_helper.rb
module AdResourceOrderx
  module OrdersHelper
  end
end

app/views/ad_resource_orderx/orders/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h4><%=@title %></h4>
<%= simple_form_for @order do |f| %>    

  <%= f.input :order_date, :label => t("Order Date"), :as => :string %> 
  <%= f.input :customer_name_autocomplete, :input_html => { data: {autocomplete_source: kustomerx.autocomplete_customers_path}}, :placeholder => t("Enter keyword"), :label => t("Customer") if @customer.blank? %>
  <%= f.input :resource_id, :label => t('Select Resource'), :collection => AdResourceOrderx.resource_class.where(:in_service => true).order('id'), :include_blank => true %>
  <%= f.input :order_total, :label => t("Order Total($)") %>
  <%= f.input :unit_price, :label => t("Unit Price($)") %>
  <%= f.input :other_charge, :label => t("Other Charge($)") %>
  <%= f.input :tax, :label => t("Tax($)") %> 
  <%= f.input :customer_po, :label => t("Customer PO#") %>
  <%= f.input :standard_price, :label => t("Standard Price($)") %>
  <%= f.input :order_detail, :label => t("Order Detail"), :input_html => {:rows => 3} %>
  <%= f.input :order_start_date, :label => t("Start Date"), :as => :string %> 
  <%= f.input :order_end_date, :label => t("End Date"), :as => :string %> 
  <%= f.input :sales_id, :label => t('Sales'), :collection => Authentify::UsersHelper::return_users('sales', 'ad_resource_orderx_orders'), :label_method => :name, :value_method => :id,
              :include_blank => true %>
  <%= f.input :last_updated_by_name, :label => t('Last Updated By'), :input_html => {:value => @order.last_updated_by.name} if @order.last_updated_by_id.present? %> 
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>

<% end %>

app/views/ad_resource_orderx/orders/_form_list.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<div class="pagination"><%= will_paginate models %></div>
    <h4><%=@title %></h>
    <table class="table table-striped">
		<tr>
			<th>#</th>
			<th><%= t('Order Date') %></th>
			<th><%= t('Customer') %></th>
			<th><%= t('Ad Resource') %></th>
			<th><%= t('Order Total($)') %></th>
			<th><%= t('Order Start Date') %></th>
			<th><%= t('Order End Date') %></th>			
			<th><%= t('WF State') %></th>
			<th><%= t('Sales') %></th>
			<th></th>
			<th></th>
			<th></th>
			<th></th>
			
		</tr>
		<% models.each do |r| %>
		  <tr>
		  	<% unless has_action_right?('show', params[:controller], r) %>
		  	  <td><%= prt(r, :id) %></td>
		  	<% else %>
		  	  <td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{order_path(r)}" %></td>
		  	<% end %>
		  	<td><%= r.order_date.strftime("%Y/%m/%d") %></td>
		  	<td><%= AdResourceOrderx.customer_class.find_by_id(r.customer_id).name if r.customer_id.present? %></td>
		  	<td><%= AdResourceOrderx.resource_class.find_by_id(r.resource_id).name if r.resource_id %></td>
		  	<td><%= number_with_precision(prt(r, :order_total), precision: 2, separator: '.') %></td>
			<td><%= r.order_start_date.strftime("%Y/%m/%d") if r.order_start_date.present? %></td>
			<td><%= r.order_end_date.strftime("%Y/%m/%d") if r.order_end_date.present? %></td> 
			<td><%= t(prt(r, :wf_state).humanize.titleize) if r.wf_state.present? %></td>
			<td><%= prt(r, 'sales.name') if r.sales_id.present? %></td>    
			<td><%= link_to t('Submit Order'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_order_path(r, :wf_event => 'submit', :resource_id => r.id)}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'initial_state' && has_action_right?('submit', params[:controller], r) %></td>
			<td><%= link_to t('CSO ') + t('Approve'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_order_path(r, :wf_event => 'cso_approve', :resource_id => r.id)}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'cso_reviewing' && has_action_right?('cso_approve', params[:controller], r) %></td>
			<td><%= link_to t('CSO ') + t('Reject'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_order_path(r, :wf_event => 'cso_reject', :resource_id => r.id)}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'cso_reviewing' && has_action_right?('cso_reject', params[:controller], r) %></td>
			<td><%= link_to t('GM ') + t('Approve'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_order_path(r, :wf_event => 'gm_approve', :resource_id => r.id)}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'gm_reviewing' && has_action_right?('gm_approve', params[:controller], r) %></td>
			<td><%= link_to t('GM ') + t('Reject'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_order_path(r, :wf_event => 'gm_reject', :resource_id => r.id)}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'gm_reviewing' && has_action_right?('gm_reject', params[:controller], r) %></td>
		    <td><%= link_to t('GM ') + t('Rewind'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_order_path(r, :wf_event => 'gm_rewind', :resource_id => r.id)}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'gm_reviewing' && has_action_right?('gm_rewind', params[:controller], r) %></td>
		    <td><%= link_to t('Sign Contract'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI.escape event_action_order_path(r, :wf_event => 'sign_contract', :resource_id => r.id)}", :class => BUTTONS_CLS['action']  if r.wf_state.present? && r.wf_state == 'approved' && has_action_right?('sign_contract', params[:controller], r) %></td>
		    <td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_order_path(r)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
			
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('New Order'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape new_order_path() }", :class => BUTTONS_CLS['action']  if has_action_right?('create', params[:controller]) %>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Open Process'), SUBURI + "/authentify/view_handler?index=1&url=#{list_open_process_orders_path()}", :class => BUTTONS_CLS['action']  if  has_action_right?('list_open_process', params[:controller]) %>
	    </th>
	  </tr>
	</table>

<% end %>	

app/views/ad_resource_orderx/orders/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h4><%=@title %></h4>
<%= simple_form_for @order do |f| %>    

  <%= f.input :order_date, :label => t("Order Date"), :as => :string %> 
  <%#= f.input :customer_name_autocomplete, :input_html => { data: {autocomplete_source: SUBURI + kustomerx.autocomplete_customers_path}}, :placeholder => t("Enter keyword"), :label => t("Customer") if @customer.blank? %>
  <%= f.input :customer_id, :label => t('Customer'), :collection => AdResourceOrderx.customer_class.order('id'), :include_blank => true %>
  <%= f.input :resource_id, :label => t('Ad Resource'), :collection => AdResourceOrderx.resource_class.where(:in_service => true).order('id'), :include_blank => true %>
  <%= f.input :order_total, :label => t("Order Total($)") %>
  <%= f.input :unit_price, :label => t("Unit Price($)") %>
  <%= f.input :other_charge, :label => t("Other Charge($)") %>
  <%= f.input :tax, :label => t("Tax($)") %> 
  <%= f.input :customer_po, :label => t("Customer PO#") %>
  <%= f.input :standard_price, :label => t("Standard Price($)") %>
  <%= f.input :order_detail, :label => t("Order Detail"), :input_html => {:rows => 3} %>
  <%= f.input :order_start_date, :label => t("Start Date"), :as => :string %> 
  <%= f.input :order_end_date, :label => t("End Date"), :as => :string %> 
  <%= f.input :sales_id, :label => t('Sales'), :collection => Authentify::UsersHelper::return_users('sales', 'ad_resource_orderx_orders'), :label_method => :name, :value_method => :id,
              :include_blank => true %>
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save'), :class => BUTTONS_CLS['action'] %>  
<% end %>

<% end %>

app/views/ad_resource_orderx/orders/create.html.erb
<h1>Rfqs#create</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/create.html.erb</p>

app/views/ad_resource_orderx/orders/edit.html.erb
 
<%= render 'form'  %>
 

  
 

app/views/ad_resource_orderx/orders/index.html.erb
 
	<%= render partial: 'form_list', locals: {models: @orders} %>
 

app/views/ad_resource_orderx/orders/list_open_process.html.erb
<div id="main_body">
	<h4><%=@title %></h4>
 
	<%= render partial: 'form_list', locals: {models: @orders} %>
 
</div>

app/views/ad_resource_orderx/orders/new.html.erb
<%= render 'form_new' %>

app/views/ad_resource_orderx/orders/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>

<h4><%=@title %></h4>

<p>
  <b><%= t('Order Date') %></b>
  <%= @order.order_date.strftime("%Y/%m/%d") %>
</p>

<p>
  <b><%= t('Customer') %></b>
  <%= @order.customer.name %>
</p>
<p>
  <b><%= t('Ad Resource') %></b>
  <%= @order.resource.name %>
</p>
<p>
  <b><%= t('Order Detail') %></b>
  <%= @order.order_detail %>
</p>
<p>
  <b><%= t('Order Total($)')  %></b>
  <%= number_with_precision(@order.order_total, :precision => 2) %>
</p>
<p>
  <b><%= t('Unit Price($)')  %></b>
  <%= number_with_precision(@order.unit_price, :precision => 2) if @order.unit_price.present? %>
</p>
<p>
  <b><%= t('Other Charge($)')  %></b>
  <%= number_with_precision(@order.other_charge, :precision => 2) if @order.other_charge.present? %>
</p>
<p>
  <b><%= t('Tax($)')  %></b>
  <%= number_with_precision(@order.tax, :precision => 2) if @order.tax.present? %>
</p>
<p>
  <b><%= t('Standard Price($)')  %></b>
  <%= number_with_precision(@order.standard_price, :precision => 2) if @order.standard_price.present? %>
</p>
<p>
  <b><%= t('Order Start Date') %></b>
  <%= @order.order_start_date.strftime("%Y/%m/%d") if @order.order_start_date.present? %>
</p>
<p>
  <b><%= t('Order End Date') %></b>
  <%= @order.order_end_date.strftime("%Y/%m/%d") if @order.order_end_date.present? %>
</p>
<p>
  <b><%= t('Sales') %></b>
  <%= @order.sales.name if @order.sales_id.present? %>
</p>
<p>
  <b><%= t('GM Approved By') %>:</b>
  <%= Authentify::User.find_by_id(@order.gm_approved_by_id).name if @order.gm_approved_by_id.present? %>
</p>
<p>
  <b><%= t('GM Approved') %>:</b>
  <%= @order.gm_approved ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('GM Approved Date') %>:</b>
  <%= @order.gm_approve_date.strftime("%Y/%m/%d") if @order.gm_approve_date.present? %>
</p>
<p>
  <b><%= t('WF State') %>:</b>
  <%= t(@order.wf_state.humanize.titleize) if @order.wf_state.present? %>
</p>
<p>
  <b><%= t('Last Updated By') %>:</b>
  <%= @order.last_updated_by.name if @order.last_updated_by_id.present? %>
</p>
<p>
<% if @order.wf_state.present? %>
  <b><%=t('Workflow History')%>:</b>
  <% StateMachineLogx::Log.where('resource_id = ? AND resource_string = ?', @order.id, params[:controller]).order('created_at DESC').each do |t| %>
    <li><%= t.created_at.strftime("%Y/%m/%d") %>,&nbsp; <%= t.action_by_name %>,&nbsp; <%=t(t.from)%>,&nbsp; <%=t(t.event.capitalize) %>,&nbsp; <%=t(t.to)%>,&nbsp;<%= t.comment %> </li>
  <% end %>
<% end %>	
</p>
<p>
  <b><%= t('LOG：') %></b>
  <% Commonx::Log.where('resource_id = ? AND resource_name = ?', @order.id, params[:controller].sub('/', '_')).order("created_at DESC").each do |t| %>
    <li><%= t.created_at.strftime("%Y/%m/%d") %>,&nbsp; <%= t.last_updated_by.name %>,&nbsp; <%= t.log %></li>
  <% end %>
</p>
	<table class="table table-striped">
	  <tr>
	    <th>
  			<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
  			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    	    <%= link_to t('New Log'), SUBURI + commonx.new_log_path(:resource_id => @order.id, :resource_name => params[:controller], :subaction => 'ad_resource_order',
    	     :format => :js), :remote => true, :id => 'new_log_link' , :class => BUTTONS_CLS['action'] if has_action_right?('create_ad_resource_order', 'commonx/logs') %>
          </th>
	  </tr>
	</table>     	


<% end %>

app/views/ad_resource_orderx/orders/update.html.erb
<h1>Rfqs#update</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/update.html.erb</p>